packages:
  - apps/web
  - apps/desktop
  - apps/electron
  - apps/api
  - packages/*

catalog:
  lucide-react: ^0.561.0
  tailwind-merge: ^3.6.0
  tailwindcss: ^4.3.3
  typescript: ^6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.3.3
  vitest: npm:@voidzero-dev/vite-plus-test@latest

onlyBuiltDependencies:
  - core-js
  - es5-ext
  - esbuild
  - futurescript
  - protobufjs
  - sharp
  - workerd

overrides:
  '@better-auth/api-key': 1.7.3
  '@better-auth/core': 1.7.3
  '@better-auth/utils': 0.4.2
  better-auth: 1.7.3
  vite: 'catalog:'
  vitest: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
