/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboard/layout'
import { Route as OgRouteImport } from './routes/og'
import { Route as DashboardUserLayoutRouteImport } from './routes/_dashboard/$user/layout'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardUserIndexRouteImport } from './routes/_dashboard/$user/index'
import { Route as DashboardViewerIndexRouteImport } from './routes/_dashboard/viewer/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardUserReposIndexRouteImport } from './routes/_dashboard/$user/repos/index'
import { Route as DashboardUserSearchIndexRouteImport } from './routes/_dashboard/$user/search/index'
import { Route as DashboardUserStarsIndexRouteImport } from './routes/_dashboard/$user/stars/index'
import { Route as DashboardUserReposRepoIndexRouteImport } from './routes/_dashboard/$user/repos/$repo/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUserLayoutRoute = DashboardUserLayoutRouteImport.update({
  id: '/$user',
  path: '/$user',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUserIndexRoute = DashboardUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardUserLayoutRoute,
} as any)
const DashboardViewerIndexRoute = DashboardViewerIndexRouteImport.update({
  id: '/viewer/',
  path: '/viewer/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUserReposIndexRoute = DashboardUserReposIndexRouteImport.update({
  id: '/repos/',
  path: '/repos/',
  getParentRoute: () => DashboardUserLayoutRoute,
} as any)
const DashboardUserSearchIndexRoute =
  DashboardUserSearchIndexRouteImport.update({
    id: '/search/',
    path: '/search/',
    getParentRoute: () => DashboardUserLayoutRoute,
  } as any)
const DashboardUserStarsIndexRoute = DashboardUserStarsIndexRouteImport.update({
  id: '/stars/',
  path: '/stars/',
  getParentRoute: () => DashboardUserLayoutRoute,
} as any)
const DashboardUserReposRepoIndexRoute =
  DashboardUserReposRepoIndexRouteImport.update({
    id: '/repos/$repo/',
    path: '/repos/$repo/',
    getParentRoute: () => DashboardUserLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/og': typeof OgRoute
  '/$user': typeof DashboardUserLayoutRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$user/': typeof DashboardUserIndexRoute
  '/viewer/': typeof DashboardViewerIndexRoute
  '/$user/repos/': typeof DashboardUserReposIndexRoute
  '/$user/search/': typeof DashboardUserSearchIndexRoute
  '/$user/stars/': typeof DashboardUserStarsIndexRoute
  '/$user/repos/$repo/': typeof DashboardUserReposRepoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/og': typeof OgRoute
  '/auth': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$user': typeof DashboardUserIndexRoute
  '/viewer': typeof DashboardViewerIndexRoute
  '/$user/repos': typeof DashboardUserReposIndexRoute
  '/$user/search': typeof DashboardUserSearchIndexRoute
  '/$user/stars': typeof DashboardUserStarsIndexRoute
  '/$user/repos/$repo': typeof DashboardUserReposRepoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardLayoutRouteWithChildren
  '/og': typeof OgRoute
  '/_dashboard/$user': typeof DashboardUserLayoutRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboard/$user/': typeof DashboardUserIndexRoute
  '/_dashboard/viewer/': typeof DashboardViewerIndexRoute
  '/_dashboard/$user/repos/': typeof DashboardUserReposIndexRoute
  '/_dashboard/$user/search/': typeof DashboardUserSearchIndexRoute
  '/_dashboard/$user/stars/': typeof DashboardUserStarsIndexRoute
  '/_dashboard/$user/repos/$repo/': typeof DashboardUserReposRepoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/og'
    | '/$user'
    | '/auth/'
    | '/api/auth/$'
    | '/$user/'
    | '/viewer/'
    | '/$user/repos/'
    | '/$user/search/'
    | '/$user/stars/'
    | '/$user/repos/$repo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/og'
    | '/auth'
    | '/api/auth/$'
    | '/$user'
    | '/viewer'
    | '/$user/repos'
    | '/$user/search'
    | '/$user/stars'
    | '/$user/repos/$repo'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/og'
    | '/_dashboard/$user'
    | '/auth/'
    | '/api/auth/$'
    | '/_dashboard/$user/'
    | '/_dashboard/viewer/'
    | '/_dashboard/$user/repos/'
    | '/_dashboard/$user/search/'
    | '/_dashboard/$user/stars/'
    | '/_dashboard/$user/repos/$repo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  OgRoute: typeof OgRoute
  AuthIndexRoute: typeof AuthIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/$user': {
      id: '/_dashboard/$user'
      path: '/$user'
      fullPath: '/$user'
      preLoaderRoute: typeof DashboardUserLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/$user/': {
      id: '/_dashboard/$user/'
      path: '/'
      fullPath: '/$user/'
      preLoaderRoute: typeof DashboardUserIndexRouteImport
      parentRoute: typeof DashboardUserLayoutRoute
    }
    '/_dashboard/viewer/': {
      id: '/_dashboard/viewer/'
      path: '/viewer'
      fullPath: '/viewer/'
      preLoaderRoute: typeof DashboardViewerIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/$user/repos/': {
      id: '/_dashboard/$user/repos/'
      path: '/repos'
      fullPath: '/$user/repos/'
      preLoaderRoute: typeof DashboardUserReposIndexRouteImport
      parentRoute: typeof DashboardUserLayoutRoute
    }
    '/_dashboard/$user/search/': {
      id: '/_dashboard/$user/search/'
      path: '/search'
      fullPath: '/$user/search/'
      preLoaderRoute: typeof DashboardUserSearchIndexRouteImport
      parentRoute: typeof DashboardUserLayoutRoute
    }
    '/_dashboard/$user/stars/': {
      id: '/_dashboard/$user/stars/'
      path: '/stars'
      fullPath: '/$user/stars/'
      preLoaderRoute: typeof DashboardUserStarsIndexRouteImport
      parentRoute: typeof DashboardUserLayoutRoute
    }
    '/_dashboard/$user/repos/$repo/': {
      id: '/_dashboard/$user/repos/$repo/'
      path: '/repos/$repo'
      fullPath: '/$user/repos/$repo/'
      preLoaderRoute: typeof DashboardUserReposRepoIndexRouteImport
      parentRoute: typeof DashboardUserLayoutRoute
    }
  }
}

interface DashboardUserLayoutRouteChildren {
  DashboardUserIndexRoute: typeof DashboardUserIndexRoute
  DashboardUserReposIndexRoute: typeof DashboardUserReposIndexRoute
  DashboardUserSearchIndexRoute: typeof DashboardUserSearchIndexRoute
  DashboardUserStarsIndexRoute: typeof DashboardUserStarsIndexRoute
  DashboardUserReposRepoIndexRoute: typeof DashboardUserReposRepoIndexRoute
}

const DashboardUserLayoutRouteChildren: DashboardUserLayoutRouteChildren = {
  DashboardUserIndexRoute: DashboardUserIndexRoute,
  DashboardUserReposIndexRoute: DashboardUserReposIndexRoute,
  DashboardUserSearchIndexRoute: DashboardUserSearchIndexRoute,
  DashboardUserStarsIndexRoute: DashboardUserStarsIndexRoute,
  DashboardUserReposRepoIndexRoute: DashboardUserReposRepoIndexRoute,
}

const DashboardUserLayoutRouteWithChildren =
  DashboardUserLayoutRoute._addFileChildren(DashboardUserLayoutRouteChildren)

interface DashboardLayoutRouteChildren {
  DashboardUserLayoutRoute: typeof DashboardUserLayoutRouteWithChildren
  DashboardViewerIndexRoute: typeof DashboardViewerIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardUserLayoutRoute: DashboardUserLayoutRouteWithChildren,
  DashboardViewerIndexRoute: DashboardViewerIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  OgRoute: OgRoute,
  AuthIndexRoute: AuthIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
